GOOGLE_APPLICATION_CREDENTIALS = "/Users/briannamitchell/.config/gcp/vertex-sa.json"

GOOGLE_API_KEY = "AIzaSyBy-Btrbaa0CSU3KJE9HSeg1-0nzzcvmW0"

GOOGLE_CLOUD_PROJECT = "gen-lang-client-0343643614"
GCLOUD_PROJECT = "gen-lang-client-0343643614"
GOOGLE_CLOUD_LOCATION = "us-east4"

CHROMA_API_KEY = "ck-8esgjZSsSfuNwaEMgJaKnhY3mw44ij8LHwERD1dbYLE1"

CHROMA_TENANT = "b777ba3a-1135-4073-a88b-445ba4eaae9e"

CHROMA_DATABASE = "Demo"
